### ISSUE TITLE
Can you support multi-threaded downloads?

### ISSUE THREAD

**Issue by Vzz1c** [rgreinho/trauma#78] opened 2023-11-01 13:07 UTC
According to my testing, this is a single-threaded download, is there a plan to support multi-threaded downloads?

**Comment by rgreinho** [comment] 2023-11-01 14:21
Not at the moment, but I'll definitely review the PR if someone submits a patch.

**Comment by rgreinho** [comment] 2023-11-01 14:23
Closing as duplicate of #65.

**Closed by rgreinho** 2023-11-01 14:23 UTC
Labels: kind/enhancement
