### ISSUE TITLE
Only showing the main progress bar and hiding all the child progress bars

### ISSUE THREAD

**Issue by akashlama1998-icloud** [rgreinho/trauma#41] opened 2022-10-15 13:46 UTC
I read every page of the documentation and even tried it myself but couldn't figure out a way to only show the main progress bar. Can you please help me?

**Comment by rgreinho** [comment] 2022-10-15 19:31
You should be able to set the child progress bar options to `hidden` with [ProgressBarOpts::hidden()](https://docs.rs/trauma/latest/trauma/downloader/struct.ProgressBarOpts.html#method.hidden).

**Comment by akashlama1998-icloud** [comment] 2022-10-16 09:30
I tried that but it just reverts child progress bar back to default rather than hiding it.

**Comment by rgreinho** [comment] 2022-10-16 16:06
Oh! Since trauma calls the `hidden()` function of the indicatif library, that might also be a bug there. I'll try to see how to reproduce that problem. I see that there is also a newer version of indicatif that we may want to try.

**Comment by akashlama1998-icloud** [comment] 2022-10-17 07:31
Yes, thank you it would be a great help, and I'll be waiting to the update.

**Comment by rgreinho** [comment] 2022-11-20 01:37
This issue should be fixed in 2.1.1.

If you are still encountering the problem, feel free to re-open this issue and post a minimal reproducible example.

**Closed by rgreinho** 2022-11-20 01:37 UTC
Labels: kind/bug, feedback/question
